# Generated by Django 5.0.7 on 2024-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("teacher_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
    ]
