# Generated by Django 5.0.7 on 2024-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_coursemodel_course_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matric", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=10)),
                ("course_name", models.CharField(max_length=100)),
                ("teacher_id", models.CharField(max_length=20)),
                (
                    "records",
                    models.ManyToManyField(
                        related_name="attendances", to="mainapp.attendancerecord"
                    ),
                ),
            ],
        ),
    ]
