# Generated by Django 5.0.7 on 2024-09-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_attendancerecord_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="course_code",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="course_name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="teacher_id",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="matric",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="time",
            field=models.CharField(max_length=10000),
        ),
    ]
