# Generated by Django 5.0.7 on 2024-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_attendance_course_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matric", models.CharField(max_length=10000, unique=True)),
                ("name", models.CharField(max_length=10000)),
                ("level", models.CharField(max_length=10000)),
                ("department", models.CharField(max_length=10000)),
            ],
        ),
    ]
