# Generated by Django 5.0.7 on 2024-09-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_studentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="department",
            field=models.CharField(default="dept", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="level",
            field=models.CharField(default="level", max_length=10000),
            preserve_default=False,
        ),
    ]
