# Generated by Django 5.0.7 on 2024-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_attendancerecord_department_attendancerecord_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="course_id",
            field=models.CharField(default="fake_id", max_length=10000),
            preserve_default=False,
        ),
    ]
