# Generated by Django 5.0.7 on 2024-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_studentmodel_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="matric",
            field=models.CharField(max_length=10000),
        ),
    ]
